# Generated by Django 3.0.5 on 2020-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Assigned',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='type',
            new_name='status',
        ),
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default='This is the body of teh value'),
            preserve_default=False,
        ),
    ]
