# Generated by Django 3.0.5 on 2020-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200409_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
